name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Debug - Print PATH
      run: docker run myapp echo $PATH
    - name: Build the Docker image
      run: docker build . -t myapp
    
    - name: Run unit and integration tests
      run: docker run myapp pytest
    
    - name: Login to DockerHub
      if: success() && github.event_name == 'push'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push image to DockerHub
      if: success() && github.event_name == 'push'
      run: |
        docker tag myapp mydockerhubusername/myapp:latest
        docker push mydockerhubusername/myapp:latest
